/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.2.446 */
/* Module Version: 4.6 */
/* Mon Jun 22 18:36:20 2020 */

/* parameterized module instance */
LEDS_DIV12 __ (.Clock( ), .Clk_En( ), .Aclr( ), .Q( ));
