/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.2.446 */
/* Module Version: 5.7 */
/* Wed Jun 24 13:26:44 2020 */

/* parameterized module instance */
PLL1 __ (.CLKI( ), .CLKOP( ), .CLKOS( ), .CLKOS2( ), .CLKOS3( ), 
    .LOCK( ));
