//Verilog testbench template generated by SCUBA Diamond (64-bit) 3.11.2.446
`timescale 1 ns / 1 ps
module tb;
    reg Clk = 0;
    reg Enb = 0;
    reg Rst = 0;
    wire [15:0] Dout;

    integer i0 = 0, i1 = 0, i2 = 0, i3 = 0;

    GSR GSR_INST (.GSR(1'b1));
    PUR PUR_INST (.PUR(1'b1));

    LFSR1 u1 (.Clk(Clk), .Enb(Enb), .Rst(Rst), .Dout(Dout)
    );

    initial
    begin
       Enb <= 1'b1;
    end
endmodule