//Verilog testbench template generated by SCUBA Diamond (64-bit) 3.11.2.446
`timescale 1 ns / 1 ps
module tb;
    reg [4:0] Address = 5'b0;
    wire [0:0] Q;

    integer i0 = 0, i1 = 0;

    GSR GSR_INST (.GSR(1'b1));
    PUR PUR_INST (.PUR(1'b1));

    TABLE_3_2 u1 (.Address(Address), .Q(Q)
    );

    initial
    begin
       Address <= 0;
      #100;
      #10;
      for (i1 = 0; i1 < 35; i1 = i1 + 1) begin
        #10;
         Address <= Address + 1'b1;
      end
    end
endmodule